name: daily update

on:
  workflow_dispatch:
  schedule:
  #https://jasonet.co/posts/scheduled-actions/
  #       ┌───────────── minute (0 - 59)
  #       │ ┌───────────── hour (0 - 23)
  #       │ │ ┌───────────── day of the month (1 - 31)
  #       │ │ │ ┌───────────── month (1 - 12)
  #       │ │ │ │ ┌───────────── day of the week (0 - 6) Sun-Mon...Sat
  #       │ │ │ │ │
  #       │ │ │ │ │
  #       │ │ │ │ │
  #       * * * * *
  - cron: '0 7 ? * 1,2,3,4,5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"


    - name: Install docs dependencies
      run: |
        sudo apt-get install -y poppler-utils
        pip install --upgrade pip
        pip install --upgrade pip ipython ipykernel
        ipython kernel install --name "python3" --user
        pip install ".[docs]"

    - name: Build docs
      working-directory: ./docs
      run: |
        make html

    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "### new gh-pages outputs! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "$(git ls-files -mo "*md")" >> $GITHUB_STEP_SUMMARY
        echo "### new gh-pages files! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "$(git ls-files -mo)" >> $GITHUB_STEP_SUMMARY
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Check for modified files
      id: git-check
      run: |
        echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
    - name: Push changes
      if: steps.git-check.outputs.modified == 'true'
      run: |
        echo "### new outputs! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "$(git ls-files -mo "*md")" >> $GITHUB_STEP_SUMMARY
        echo "### new files! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "$(git ls-files -mo)" >> $GITHUB_STEP_SUMMARY
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "new files"
        git push
    # ===============================
